### ISSUE TITLE
[Bug]: Memory Buffer Not Updating

### ISSUE THREAD

**Issue by ciaran-regan-ie** [sudame/PolyaUrnSimulator#3]
### Bug description

The memory buffer of interacting agents is not updating according to the strategy during the `step` function. This is because we are appending the interaction to the `env.history` before running ` if !((caller, called) ∈ env.history) && !((called, caller) ∈ env.history)`, which is where the strategy is used to update the memory buffer.

### How to reproduce

To verify this, I ran the simulation with a `println` in step 4 of the model. Nothing was printed, verifying step 4 was not occurring.

### Expected behavior

Strategy should update the memory buffer after each interaction.

### Actual behavior

Memory buffer is never updated. Strategy is never used.

### Environment

Mac OS

**Comment by ciaran-regan-ie** [comment]
The fix for this is very simple. I will make a PR

**Comment by Okabe-Junya** [comment]
Great!!!

**Comment by Okabe-Junya** [comment]
@ciaran-regan-ie 

Please make me a reviewer and I'll look at it later.
