### ISSUE TITLE
[Bug]: SSW Strategy not Working

### ISSUE THREAD

**Issue by ciaran-regan-ie** [sudame/PolyaUrnSimulator#5]
### Bug description

When you try to run a simulation with the SSW strategy there is an error. 

`BoundsError: attempt to access 0-element Vector{Tuple{Int64, Int64}} at index [0]`

### How to reproduce

Try to run the simulator using SSW strategy, or try to run runtests.jl

### Expected behavior

The simulation should run as expected.

### Actual behavior

`BoundsError: attempt to access 0-element Vector{Tuple{Int64, Int64}} at index [0]`

### Environment

MacOS

### Additional context

See branch fix-ssw for possible solution.

**Comment by ciaran-regan-ie** [comment]
これは、前回の PR で `append!(env.history, [(caller, called)])` を移動したことが原因でした。

**Comment by Okabe-Junya** [comment]
#8 で解決
